## Numpy
nummpy is a python library used for scientific computations and numerical operations

### Arrays

Array is a collection of elements of the same data types stored in a  multidimensional structure. it provides an efficient way to store and perform operations on numerical data.

+ Number of dimensions in an array is called its rank.
+ Size of  the array along its dimension is called shape.
+ Elements are accessed uing [] brackets and are created using python lists

In [79]:
arr = np.zeros((2,3))
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [83]:
arr = np.identity(2)
arr


array([[1., 0.],
       [0., 1.]])

In [87]:
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

In [89]:
a = np.random.rand()
a

0.753407913476104

In [94]:
a = np.random.rand(3)
a

array([0.30544909, 0.12218595, 0.90459386])

In [99]:
a = np.diag((2,3))
a

array([[2, 0],
       [0, 3]])

In [104]:
a = np.full((2, 3), 3)
a

array([[3, 3, 3],
       [3, 3, 3]])

### Question Number 1: Create 1D NUmpy array containing the value:10, 20, 30, 40, 50.

In [73]:

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [12]:
print(arr)

[10 20 30 40 50]


### Question number 2: Create a 2D numpy array representing the following matrix:
+ 123
+ 456
+ 789

In [15]:
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [16]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create a NumPy array of shape (3, 4) filled entirely with zeros.


In [22]:
zero_matrix = np.zeros((3, 4))

In [26]:

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Using NumPy's arange() function, create an array containing odd numbers from 1 to
19.

In [29]:
odd_arr = np.arange(1, 20, 2)

In [30]:
odd_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Using NumPy's linspace() function, create an array of 5 evenly spaced values
between 0 and 100.

In [33]:
arr = np.linspace(0, 100, 5)

In [34]:
arr


array([  0.,  25.,  50.,  75., 100.])

In [36]:
arr = np.ones((2, 3))

In [37]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
grid = np.linspace(0, 10, num = 5)

In [40]:
grid

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
a = np.arange(6)

In [42]:
a

array([0, 1, 2, 3, 4, 5])

In [43]:
matrix = a.reshape((2,3))

In [44]:
matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
transposed = matrix.T

In [47]:
transposed

array([[0, 3],
       [1, 4],
       [2, 5]])

Use the numpy add function to add the values 34 and 29 in the cell below.


In [55]:
arr = np.add(34, 29)
arr

np.int64(63)

Declare a new array with contents [5,4,3,2,1] and slice it to select the last 3 items.


In [58]:
arr = np.array([5, 4, 3, 2, 1])
arr[-3:]

array([3, 2, 1])

Select all the elements in the array below excluding the last one


In [59]:
arr[:-1]

array([5, 4, 3, 2])

Use arr as defined in 2.3. Exclude the last element from the list, but now only select
every 3rd element. Remember the third index indicates stride

In [66]:
arr = np.array([5, 4, 3, 2, 1])

# Slice excluding the last element, with a stride of 3
result = arr[:-1:3]

print(result)

[5 2]


You’ll need to combine array comparisons and logical operators to solve this one.
Find out the values in the following array that are greater than 3 AND less than 7.
The output should be a boolean array

In [71]:
arr = np.array([5, 4, 3, 2, 1, 7, 9 ,8])
result = (arr > 3) & (arr < 7)


In [72]:
result

array([ True,  True, False, False, False, False, False, False])